export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST';
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const UNIQUE_CATEGORIES_REQUEST = 'UNIQUE_CATEGORIES_REQUEST';
export const UNIQUE_CATEGORIES_SUCCESS = 'UNIQUE_CATEGORIES_SUCCESS';
export const UNIQUE_CATEGORIES_FAIL = 'UNIQUE_CATEGORIES_FAIL';

export const UNIQUE_SIZES_REQUEST = 'UNIQUE_SIZES_REQUEST';
export const UNIQUE_SIZES_SUCCESS = 'UNIQUE_SIZES_SUCCESS';
export const UNIQUE_SIZES_FAIL = 'UNIQUE_SIZES_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
